In [1]:
import requests as req
import pandas as pd

In [2]:
#se configura header y pagina a scrappear#

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "x-nextjs-data": "1"
}

response = req.get("https://www.fotmob.com/api/data/leagueseasondeepstats?id=38&season=27185&type=players&stat=goal_assist", 
             headers=headers)

print(response.status_code)

200

In [3]:
#obtenemos los datos en formato json y los imprimimos para ver su estructura#

data = response.json()
print(data.keys())
print(type(data))

dict_keys(['statsData', 'seasons', 'statsList', 'leagueDetails', 'type', 'teamName', 'currentSeasonId', 'currentStatName', 'teamColors', 'substatTitle', 'substatLocalizedTitleId'])
<class 'dict'>

In [4]:
print(type(data['statsData']))
print(data['statsData'][0])

<class 'list'>
{'id': 1053284, 'teamId': 1954, 'name': 'Dejan Zukic', 'position': 85, 'substatValue': {'value': 7.9, 'format': 'fraction', 'fractions': 1}, 'statValue': {'name': 'goal_assist', 'value': 10, 'format': 'number', 'fractions': 0}, 'rank': 1, 'type': 'players'}

In [5]:
print(type(data['statsList']))
# Si es una lista, mira el primer elemento:
print(data['statsList'][13]) 
# O si es un diccionario, mira sus llaves:
# print(data['statsList'].keys())

<class 'list'>
{'name': 'total_att_assist', 'localizedTitleId': 'chances_created', 'title': 'Chances created', 'category': 'Attacking', 'localizedCategoryId': 'attack'}

In [6]:
#sacamos los datos de id, nombre y valor de cada jugador y los guardamos en un dataframe#

asistencias = []

for jugador in (data['statsData']):
    id = jugador.get('id', {})
    nombre = jugador.get('name', {})
    valor = jugador.get('substatValue', {}).get('value')

    df_fila = {'id': id, 'nombre': nombre, 'valor': valor}

    asistencias.append(df_fila)

df_asistencias = pd.DataFrame(asistencias)
print(df_asistencias)

          id              nombre  valor
0    1053284         Dejan Zukic    7.9
1    1276078      Matthias Seidl    6.8
2    1459265       Frans Krätzig    4.6
3     638127  Johannes Eggestein    4.4
4     978170         Tomi Horvat    6.2
..       ...                 ...    ...
154  1692197        Daniel Nunoo    0.2
155  1783320     Habib Coulibaly    0.2
156  1536477    Mahamadou Diarra    0.1
157  1714633     Emmanuel Ojukwu    0.0
158  1338941        Patrik Mijic    0.0

[159 rows x 3 columns]

In [ ]:
stat_name = ["goals", "goal_assist", "expected_goals", "expected_goalsontarget", "total_scoring_att", "expected_assists_per_90","won_contest"
             , "accurate_long_balls", "poss_won_att_3rd", "defensive_contributions", "total_tackle", "interception",  "effective_clearance"]
leagues = [
    {"id": 38, "season_id": 38611, "slug": "bundesliga-players"},
    {"id": 122, "season_id": 38000, "slug": "1-liga-players"},
    { "id": 46, "season_id": 35802, "slug": "superligaen-players"},
    { "id": 212, "season_id": 38837, "slug": "nb-i-players"},
    { "id": 196, "season_id": 37304, "slug": "ekstraklasa-player" },
    { "id": 135, "season_id": 44734, "slug": "super-league-1-players" }
]
build_id = "ZL64iOcIu6K0j4uv0G7J1"

endpoint = "https://www.fotmob.com/api/data/leagueseasondeepstats"

#f"https://www.fotmob.com/api/data/{build_id}/es/leagues/{league_id}/stats/season/{season_id}/players/{stat_name}/{slug}.json"



datos_jugadores = []
for x in leagues:
    #query_params["id"] = leagues["id"]

    query_params = {
    "id": x.get("id"),
    "season": x.get("season_id"),
    "type": "players",
    "stat": stat_name,
    "slug": x.get("slug"),
    "lng": "es"
}

    for i in stat_name:


        query_params["stat"] = i

        response = req.get(endpoint, headers=headers, params=query_params)
        if response.status_code == 200:
            print(f"Request successful for league {x.get('id')} and stat {i}")
        else:
            print(f"Request failed for league {x.get('id')} and stat {i} with status code {response.status_code}")
            continue  # Skip to the next iteration if the request fails

        data = response.json()
        comprobacion_contenido = len(data.get('statsData', []))
        if comprobacion_contenido == 0:
            print(f"statData not found for league {x.get("id")} and stat {i}")
            continue #Skip to the next iteration if data is empty



        for jugador in data['statsData']:
            id = jugador.get('id', {})
            nombre = jugador.get('name', {})
            valor = jugador.get('statValue', {}).get('value')

            df_fila = {'id': id, 'nombre': nombre, 'valor': valor, 'stat': i, "league": x.get("id")}

            datos_jugadores.append(df_fila)

df_datos_jugadores = pd.DataFrame(datos_jugadores)

Request successful for league 38 and stat goals
Request successful for league 38 and stat goal_assist
Request successful for league 38 and stat expected_goals
Request successful for league 38 and stat expected_goalsontarget
Request successful for league 38 and stat total_scoring_att
Request successful for league 38 and stat expected_assists_per_90
Request successful for league 38 and stat won_contest
Request successful for league 38 and stat accurate_long_balls
Request successful for league 38 and stat poss_won_att_3rd
Request successful for league 38 and stat defensive_contributions
Request successful for league 38 and stat total_tackle
Request successful for league 38 and stat interception
Request successful for league 38 and stat effective_clearance
Request successful for league 122 and stat goals
Request successful for league 122 and stat goal_assist
Request successful for league 122 and stat expected_goals
statData not found for league 122 and stat expected_goals
Request successful for league 122 and stat expected_goalsontarget
statData not found for league 122 and stat expected_goalsontarget
Request successful for league 122 and stat total_scoring_att
Request successful for league 122 and stat expected_assists_per_90
statData not found for league 122 and stat expected_assists_per_90
Request successful for league 122 and stat won_contest
Request successful for league 122 and stat accurate_long_balls
Request successful for league 122 and stat poss_won_att_3rd
Request successful for league 122 and stat defensive_contributions
Request successful for league 122 and stat total_tackle
Request successful for league 122 and stat interception
Request successful for league 122 and stat effective_clearance
Request successful for league 46 and stat goals
Request successful for league 46 and stat goal_assist
Request successful for league 46 and stat expected_goals
Request successful for league 46 and stat expected_goalsontarget
Request successful for league 46 and stat total_scoring_att
Request successful for league 46 and stat expected_assists_per_90
Request successful for league 46 and stat won_contest
Request successful for league 46 and stat accurate_long_balls
Request successful for league 46 and stat poss_won_att_3rd
Request successful for league 46 and stat defensive_contributions
Request successful for league 46 and stat total_tackle
Request successful for league 46 and stat interception
Request successful for league 46 and stat effective_clearance
Request successful for league 212 and stat goals
Request successful for league 212 and stat goal_assist
Request successful for league 212 and stat expected_goals
statData not found for league 212 and stat expected_goals
Request successful for league 212 and stat expected_goalsontarget
statData not found for league 212 and stat expected_goalsontarget
Request successful for league 212 and stat total_scoring_att
statData not found for league 212 and stat total_scoring_att
Request successful for league 212 and stat expected_assists_per_90
statData not found for league 212 and stat expected_assists_per_90
Request successful for league 212 and stat won_contest
statData not found for league 212 and stat won_contest
Request successful for league 212 and stat accurate_long_balls
statData not found for league 212 and stat accurate_long_balls
Request successful for league 212 and stat poss_won_att_3rd
statData not found for league 212 and stat poss_won_att_3rd
Request successful for league 212 and stat defensive_contributions
statData not found for league 212 and stat defensive_contributions
Request successful for league 212 and stat total_tackle
statData not found for league 212 and stat total_tackle
Request successful for league 212 and stat interception
statData not found for league 212 and stat interception
Request successful for league 212 and stat effective_clearance
statData not found for league 212 and stat effective_clearance
Request successful for league 196 and stat goals
Request successful for league 196 and stat goal_assist
Request successful for league 196 and stat expected_goals
Request successful for league 196 and stat expected_goalsontarget
Request successful for league 196 and stat total_scoring_att
Request successful for league 196 and stat expected_assists_per_90
Request successful for league 196 and stat won_contest
Request successful for league 196 and stat accurate_long_balls
Request successful for league 196 and stat poss_won_att_3rd
Request successful for league 196 and stat defensive_contributions
Request successful for league 196 and stat total_tackle
Request successful for league 196 and stat interception
Request successful for league 196 and stat effective_clearance
Request successful for league 135 and stat goals
Request successful for league 135 and stat goal_assist
Request successful for league 135 and stat expected_goals
Request successful for league 135 and stat expected_goalsontarget
Request successful for league 135 and stat total_scoring_att
Request successful for league 135 and stat expected_assists_per_90
Request successful for league 135 and stat won_contest
Request successful for league 135 and stat accurate_long_balls
Request successful for league 135 and stat poss_won_att_3rd
Request successful for league 135 and stat defensive_contributions
Request successful for league 135 and stat total_tackle
Request successful for league 135 and stat interception
Request successful for league 135 and stat effective_clearance

en la liga checa no tienen xg ni xa, por lo que habra que tenerlo en cuenta para ve si se sustituye esta liga o vemos si se puede extraer de otro lado

In [32]:
duplicados = df_datos_jugadores[df_datos_jugadores.duplicated(subset=["id", "stat"], keep=False)]
lista_dupl=duplicados["id"].unique().tolist()

endpoint_player = "https://www.fotmob.com/api/data/playerData?"
params_player = {"id": lista_dupl}

data_dupli = req.get(endpoint_player, headers=headers, params=params_player)
df_dupli=data_dupli.json()
print(df_dupli)

{'id': 180283, 'name': 'Fredrik Ulvestad', 'birthDate': {'utcTime': '1992-05-19T00:00:00.000Z', 'timezone': 'UTC'}, 'contractEnd': {'utcTime': '2028-06-30T00:00:00.000Z', 'timezone': 'UTC'}, 'isCoach': False, 'isCaptain': False, 'gender': 'male', 'primaryTeam': {'teamId': 8414, 'teamName': 'OB', 'onLoan': False, 'teamColors': {'color': '#205898', 'colorAlternate': '#205898', 'colorAway': '#000000', 'colorAwayAlternate': '#FFFFFF'}}, 'positionDescription': {'positions': [{'strPos': {'label': 'Defensive Midfielder', 'key': 'centerdefensivemidfielder'}, 'strPosShort': {'label': 'DM', 'key': 'centerdefensivemidfielder_short'}, 'occurences': 13, 'position': '64', 'isMainPosition': True, 'pitchPositionData': {'right': 0.5, 'top': 0.58}}, {'strPos': {'label': 'Right Midfielder', 'key': 'rightmidfielder'}, 'strPosShort': {'label': 'RM', 'key': 'rightmidfielder_short'}, 'occurences': 2, 'position': '72', 'isMainPosition': False, 'pitchPositionData': {'right': 0.83, 'top': 0.42, 'ratio': 0.27692307692307694}}, {'strPos': {'label': 'Central Midfielder', 'key': 'centermidfielder'}, 'strPosShort': {'label': 'CM', 'key': 'centermidfielder_short'}, 'occurences': 10, 'position': '74', 'isMainPosition': False, 'pitchPositionData': {'right': 0.5, 'top': 0.42, 'ratio': 0.5846153846153846}}, {'strPos': {'label': 'Attacking Midfielder', 'key': 'centerattackingmidfielder'}, 'strPosShort': {'label': 'AM', 'key': 'centerattackingmidfielder_short'}, 'occurences': 1, 'position': '84', 'isMainPosition': False, 'pitchPositionData': None}], 'primaryPosition': {'label': 'Defensive Midfielder', 'key': 'centerdefensivemidfielder'}, 'nonPrimaryPositions': [{'label': 'Right Midfielder', 'key': 'rightmidfielder'}, {'label': 'Central Midfielder', 'key': 'centermidfielder'}]}, 'injuryInformation': None, 'internationalDuty': None, 'playerInformation': [{'value': {'numberValue': 183, 'key': None, 'fallback': '183 cm'}, 'title': 'Height', 'translationKey': 'height_sentencecase'}, {'value': {'numberValue': 6, 'options': {}, 'key': None, 'fallback': 6}, 'title': 'Shirt', 'translationKey': 'shirt'}, {'value': {'numberValue': 34, 'options': {'style': 'unit', 'unit': 'year', 'unitDisplay': 'long'}, 'key': None, 'fallback': '34'}, 'title': 'Age', 'translationKey': 'age_sentencecase'}, {'value': {'key': 'right', 'fallback': 'Right'}, 'title': 'Preferred foot', 'translationKey': 'preferred_foot'}, {'value': {'key': None, 'fallback': 'Norway'}, 'title': 'Country', 'translationKey': 'country_sentencecase', 'icon': {'type': 'country', 'id': 'NOR'}, 'countryCode': 'NOR', 'nationalTeamId': 8492}, {'value': {'numberValue': 447975, 'key': None, 'fallback': '€448k'}, 'title': 'Market value', 'translationKey': 'transfer_value'}, {'value': {'dateValue': '2028-06-30', 'key': None, 'fallback': {'utcTime': '2028-06-30T00:00:00.000Z', 'timezone': 'UTC'}}, 'title': 'Contract end', 'translationKey': 'contract_end'}], 'mainLeague': {'leagueId': 46, 'leagueName': 'Superligaen', 'season': '2026/2027', 'stats': [{'title': 'Goals', 'localizedTitleId': 'goals', 'value': 0}, {'title': 'Assists', 'localizedTitleId': 'assists', 'value': 0}, {'title': 'Started', 'localizedTitleId': 'started', 'value': 0}, {'title': 'Matches', 'localizedTitleId': 'matches_uppercase', 'value': 1}, {'title': 'Minutes played', 'localizedTitleId': 'minutes_played', 'value': 22}, {'title': 'Rating', 'localizedTitleId': 'rating', 'value': 6.62}, {'title': 'Yellow cards', 'localizedTitleId': 'yellow_cards', 'value': 0}, {'title': 'Red cards', 'localizedTitleId': 'red_cards', 'value': 0}]}, 'trophies': {'playerTrophies': [{'teamId': 6265, 'teamName': 'Sivasspor', 'tournaments': [{'ccode': 'INT', 'leagueId': 151, 'leagueName': 'Turkish Cup', 'seasonsWon': ['2021/2022'], 'seasonsRunnerUp': []}]}, {'ccode': 'SWE', 'teamId': 9802, 'teamName': 'Djurgården', 'tournaments': [{'ccode': 'SWE', 'leagueId': 67, 'leagueName': 'Allsvenskan', 'seasonsWon': ['2019'], 'seasonsRunnerUp': []}, {'ccode': 'SWE', 'leagueId': -1, 'leagueName': 'Svenska Cupen', 'seasonsWon': ['2017/2018'], 'seasonsRunnerUp': []}]}, {'ccode': 'ENG', 'teamId': 8191, 'teamName': 'Burnley', 'tournaments': [{'ccode': 'ENG', 'leagueId': 48, 'leagueName': 'Championship', 'seasonsWon': ['2015/2016'], 'seasonsRunnerUp': []}]}, {'ccode': 'NOR', 'teamId': 8404, 'teamName': 'Aalesund', 'tournaments': [{'ccode': 'NOR', 'leagueId': 206, 'leagueName': 'Norgesmesterskapet', 'seasonsWon': ['2011'], 'seasonsRunnerUp': []}]}], 'coachTrophies': []}, 'recentMatches': [{'teamId': 8414, 'teamName': 'OB', 'opponentTeamId': 8113, 'opponentTeamName': 'FC Midtjylland', 'isHomeTeam': True, 'id': 5739512, 'matchDate': {'utcTime': '2026-09-19T16:00:00.000Z'}, 'matchPageUrl': '/matches/fc-midtjylland-vs-ob/29bjme#5739512', 'leagueId': 46, 'leagueName': 'Superligaen', 'stage': None, 'homeScore': 1, 'awayScore': 1, 'minutesPlayed': 22, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '6.6', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 8021, 'opponentTeamName': 'Zagłębie Lubin', 'isHomeTeam': False, 'id': 5803967, 'matchDate': {'utcTime': '2026-08-29T18:15:00.000Z'}, 'matchPageUrl': '/matches/zagebie-lubin-vs-pogon-szczecin/24mxrp#5803967', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 0, 'awayScore': 0, 'minutesPlayed': 27, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '6.1', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 10265, 'opponentTeamName': 'Wisła Kraków', 'isHomeTeam': True, 'id': 5803955, 'matchDate': {'utcTime': '2026-08-23T18:15:00.000Z'}, 'matchPageUrl': '/matches/pogon-szczecin-vs-wisa-krakow/2rkl8v#5803955', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 2, 'awayScore': 2, 'minutesPlayed': 90, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '6.9', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 84, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 89466, 'opponentTeamName': 'Motor Lublin', 'isHomeTeam': True, 'id': 5803936, 'matchDate': {'utcTime': '2026-08-08T15:30:00.000Z'}, 'matchPageUrl': '/matches/pogon-szczecin-vs-motor-lublin/26lbxv7#5803936', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 3, 'awayScore': 1, 'minutesPlayed': 90, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '7.4', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 64, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 2186, 'opponentTeamName': 'Cracovia', 'isHomeTeam': False, 'id': 5803923, 'matchDate': {'utcTime': '2026-08-03T17:00:00.000Z'}, 'matchPageUrl': '/matches/cracovia-vs-pogon-szczecin/v17vs#5803923', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 0, 'awayScore': 2, 'minutesPlayed': 30, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '6.2', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 8673, 'opponentTeamName': 'Legia Warszawa', 'isHomeTeam': True, 'id': 5803899, 'matchDate': {'utcTime': '2026-07-24T18:30:00.000Z'}, 'matchPageUrl': '/matches/pogon-szczecin-vs-legia-warszawa/2azq1p#5803899', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 0, 'awayScore': 1, 'minutesPlayed': 28, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '6.7', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 8695, 'opponentTeamName': 'Fenerbahçe', 'isHomeTeam': False, 'id': 5904696, 'matchDate': {'utcTime': '2026-07-11T17:30:00.000Z'}, 'matchPageUrl': '/matches/pogon-szczecin-vs-fenerbahce/2b7log#5904696', 'leagueId': 489, 'leagueName': 'Club Friendlies', 'stage': None, 'homeScore': 4, 'awayScore': 0, 'minutesPlayed': 58, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '6.0', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 84, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 4023, 'opponentTeamName': 'GKS Katowice', 'isHomeTeam': True, 'id': 4803721, 'matchDate': {'utcTime': '2026-05-23T15:30:00.000Z'}, 'matchPageUrl': '/matches/gks-katowice-vs-pogon-szczecin/177d4w#4803721', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 1, 'awayScore': 1, 'minutesPlayed': 90, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '6.6', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 74, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 8021, 'opponentTeamName': 'Zagłębie Lubin', 'isHomeTeam': False, 'id': 4803715, 'matchDate': {'utcTime': '2026-05-15T16:00:00.000Z'}, 'matchPageUrl': '/matches/zagebie-lubin-vs-pogon-szczecin/24mxrp#4803715', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 0, 'awayScore': 1, 'minutesPlayed': 90, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '7.1', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 74, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 1957, 'opponentTeamName': 'Jagiellonia Białystok', 'isHomeTeam': False, 'id': 4803700, 'matchDate': {'utcTime': '2026-05-09T15:30:00.000Z'}, 'matchPageUrl': '/matches/jagiellonia-biaystok-vs-pogon-szczecin/tno4d#4803700', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 3, 'awayScore': 2, 'minutesPlayed': 90, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '6.8', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 74, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 8243, 'opponentTeamName': 'Wisła Płock', 'isHomeTeam': True, 'id': 4803694, 'matchDate': {'utcTime': '2026-05-03T15:30:00.000Z'}, 'matchPageUrl': '/matches/pogon-szczecin-vs-wisa-pock/26rtbe#4803694', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 3, 'awayScore': 0, 'minutesPlayed': 90, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '7.2', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 74, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 2186, 'opponentTeamName': 'Cracovia', 'isHomeTeam': False, 'id': 4803680, 'matchDate': {'utcTime': '2026-04-25T18:15:00.000Z'}, 'matchPageUrl': '/matches/cracovia-vs-pogon-szczecin/v17vs#4803680', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 1, 'awayScore': 1, 'minutesPlayed': 90, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '6.4', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 74, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 2182, 'opponentTeamName': 'Lech Poznań', 'isHomeTeam': True, 'id': 4803676, 'matchDate': {'utcTime': '2026-04-18T18:15:00.000Z'}, 'matchPageUrl': '/matches/lech-poznan-vs-pogon-szczecin/v0cdm#4803676', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 1, 'awayScore': 2, 'minutesPlayed': 90, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '6.4', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 76, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 8028, 'opponentTeamName': 'Piast Gliwice', 'isHomeTeam': False, 'id': 4803667, 'matchDate': {'utcTime': '2026-04-13T17:00:00.000Z'}, 'matchPageUrl': '/matches/pogon-szczecin-vs-piast-gliwice/24pcga#4803667', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 0, 'awayScore': 2, 'minutesPlayed': 90, 'goals': 1, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '8.0', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 74, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 8673, 'opponentTeamName': 'Legia Warszawa', 'isHomeTeam': True, 'id': 4803658, 'matchDate': {'utcTime': '2026-04-06T15:30:00.000Z'}, 'matchPageUrl': '/matches/pogon-szczecin-vs-legia-warszawa/2azq1p#4803658', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 0, 'awayScore': 2, 'minutesPlayed': 90, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '6.6', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 64, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 8030, 'opponentTeamName': 'Lechia Gdańsk', 'isHomeTeam': False, 'id': 4803646, 'matchDate': {'utcTime': '2026-03-21T16:30:00.000Z'}, 'matchPageUrl': '/matches/pogon-szczecin-vs-lechia-gdansk/24q185#4803646', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 2, 'awayScore': 1, 'minutesPlayed': 90, 'goals': 0, 'assists': 1, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '7.1', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 64, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 8245, 'opponentTeamName': 'Korona Kielce', 'isHomeTeam': True, 'id': 4803640, 'matchDate': {'utcTime': '2026-03-16T18:00:00.000Z'}, 'matchPageUrl': '/matches/pogon-szczecin-vs-korona-kielce/26sif7#4803640', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 2, 'awayScore': 1, 'minutesPlayed': 90, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '7.6', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 66, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 4024, 'opponentTeamName': 'Raków Częstochowa', 'isHomeTeam': False, 'id': 4803632, 'matchDate': {'utcTime': '2026-03-08T16:30:00.000Z'}, 'matchPageUrl': '/matches/rakow-czestochowa-vs-pogon-szczecin/177mfj#4803632', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 2, 'awayScore': 0, 'minutesPlayed': 90, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '6.9', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 64, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 8024, 'opponentTeamName': 'Widzew Łódź', 'isHomeTeam': True, 'id': 4803623, 'matchDate': {'utcTime': '2026-02-28T13:45:00.000Z'}, 'matchPageUrl': '/matches/pogon-szczecin-vs-widzew-odz/24nyww#4803623', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 1, 'awayScore': 0, 'minutesPlayed': 90, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '7.5', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 64, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 8020, 'opponentTeamName': 'Górnik Zabrze', 'isHomeTeam': False, 'id': 4803609, 'matchDate': {'utcTime': '2026-02-21T16:45:00.000Z'}, 'matchPageUrl': '/matches/gornik-zabrze-vs-pogon-szczecin/24mle1#4803609', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 0, 'awayScore': 1, 'minutesPlayed': 90, 'goals': 1, 'assists': 0, 'yellowCards': 1, 'redCards': 0, 'ratingProps': {'rating': '8.4', 'isTopRating': True}, 'playerOfTheMatch': True, 'onBench': False, 'lineupPositionId': 64, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 8322, 'opponentTeamName': 'Arka Gdynia', 'isHomeTeam': True, 'id': 4803603, 'matchDate': {'utcTime': '2026-02-15T13:45:00.000Z'}, 'matchPageUrl': '/matches/pogon-szczecin-vs-arka-gdynia/27jfc7#4803603', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 1, 'awayScore': 0, 'minutesPlayed': 90, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '7.5', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 64, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 177361, 'opponentTeamName': 'Termalica Nieciecza', 'isHomeTeam': True, 'id': 4803597, 'matchDate': {'utcTime': '2026-02-08T11:15:00.000Z'}, 'matchPageUrl': '/matches/pogon-szczecin-vs-termalica-nieciecza/7w6qmx7#4803597', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 1, 'awayScore': 1, 'minutesPlayed': 90, 'goals': 0, 'assists': 0, 'yellowCards': 1, 'redCards': 0, 'ratingProps': {'rating': '6.5', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 74, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 89466, 'opponentTeamName': 'Motor Lublin', 'isHomeTeam': False, 'id': 4803584, 'matchDate': {'utcTime': '2026-02-01T11:15:00.000Z'}, 'matchPageUrl': '/matches/pogon-szczecin-vs-motor-lublin/26lbxv7#4803584', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 2, 'awayScore': 1, 'minutesPlayed': 90, 'goals': 1, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '8.2', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 64, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 5769, 'opponentTeamName': 'Radomiak Radom', 'isHomeTeam': True, 'id': 4803577, 'matchDate': {'utcTime': '2025-12-06T13:45:00.000Z'}, 'matchPageUrl': '/matches/radomiak-radom-vs-pogon-szczecin/1kmukn#4803577', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 2, 'awayScore': 2, 'minutesPlayed': 90, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '6.8', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 64, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 8024, 'opponentTeamName': 'Widzew Łódź', 'isHomeTeam': True, 'id': 5041507, 'matchDate': {'utcTime': '2025-12-02T19:30:00.000Z'}, 'matchPageUrl': '/matches/pogon-szczecin-vs-widzew-odz/24nyww#5041507', 'leagueId': 198, 'leagueName': 'Puchar Polski', 'stage': '1/8', 'homeScore': 0, 'awayScore': 1, 'minutesPlayed': 90, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': 0, 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 64, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 4023, 'opponentTeamName': 'GKS Katowice', 'isHomeTeam': False, 'id': 4803564, 'matchDate': {'utcTime': '2025-11-29T19:15:00.000Z'}, 'matchPageUrl': '/matches/gks-katowice-vs-pogon-szczecin/177d4w#4803564', 'leagueId': 196, 'leagueName': 'Ekstraklasa', 'stage': None, 'homeScore': 2, 'awayScore': 0, 'minutesPlayed': 90, 'goals': 0, 'assists': 0, 'yellowCards': 0, 'redCards': 0, 'ratingProps': {'rating': '6.9', 'isTopRating': False}, 'playerOfTheMatch': False, 'onBench': False, 'lineupPositionId': 64, 'playedInMatch': True}, {'teamId': 8023, 'teamName': 'Pogoń Szczecin', 'opponentTeamId': 8021, 'opponentTeamName': 'Zagłębie Lubin', 'isHomeTeam': True, 'id': 4803559, 'matchDate': {'utcTime': '2025-11-24T1

In [12]:
df_datos_jugadores[df_datos_jugadores['league'] == 135].head()

           id            nombre  valor   stat  league
9627   796504    Barnabás Varga    4.0  goals     135
9628   463291        Luka Jović    4.0  goals     135
9629  1318701    Andrews Tetteh    3.0  goals     135
9630   358937  Dimitrios Pelkas    3.0  goals     135
9631  1280328   Vicente Taborda    3.0  goals     135

In [9]:
df_datos_jugadores["league"].value_counts()

league
196    3179
46     2140
122    2136
135    2126
38     2029
212     143
Name: count, dtype: int64

In [21]:
duplicados = df_datos_jugadores[df_datos_jugadores.duplicated(subset=["id", "stat"], keep=False)]
duplicados.sort_values(by=["id","stat"]).head(20)

          id            nombre  valor            stat  league
4483  180283  Fredrik Ulvestad    0.2  expected_goals      46
6950  180283  Fredrik Ulvestad    0.1  expected_goals     196

In [19]:
df_datos_jugadores_pivoted = df_datos_jugadores.pivot(index=['id', 'nombre'], columns='stat', values='valor').reset_index()
df_datos_jugadores_pivoted.isnull().sum()

ValueError: Index contains duplicate entries, cannot reshape